### ISSUE TITLE
Fix mantl-dns depency problem with NetworkManager

### ISSUE THREAD

**Issue by GeorgFoc** [mantl/mantl-packaging#137]
Hi, 
I run into the same problem as https://github.com/mantl/mantl/issues/1859.
So if I want to install mantl, it breaks because of the line in https://github.com/asteris-llc/mantl-packaging/blob/master/mantl/mantl-dns/spec.yml:

   - NetworkManager = 1:1.0.6

When I remove the version, it works for me. 
Is there a reason why the version is pinned to 1.0.6?

**Comment by stevendborrelli** [comment]
No, I think we can make it a minimum.

**Comment by Xackery** [comment]
Had this issue as well..

**Comment by slawiek** [comment]
Confirmed. It works with newest NetworkManager version. Just to build mantl-dns rpm with removed dependency.

**Comment by Theaxiom** [comment]
I am rebuilding the packages now, I will update this issue when completed.

**Comment by Theaxiom** [comment]
mantl-dns 1.2 has been released which solves this problem, here's the repo you have to add:

```
[bintraybintray-mantl-rpm-packages]
name=bintray-mantl-rpm-packages
baseurl=https://dl.bintray.com/mantl/rpm-packages
gpgcheck=0
repo_gpgcheck=0
enabled=1
```
